language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_install:
  - sudo sh -c "echo 'extension=ldap.so' >> `php --ini | grep 'Loaded Configuration' | sed -e 's|.*:\s*||'`"

install:
  - sudo apt-get update
  - sudo apt-get install wget xz-utils default-jre ldap-utils phpunit curl -y
  - wget http://archive.apache.org/dist/directory/apacheds/dist/2.0.0-M19/apacheds-2.0.0-M19-amd64.deb
  - sudo dpkg -i apacheds-2.0.0-M19-amd64.deb
  - composer self-update
  - sudo rm -rf /var/lib/apacheds-2.0.0-M19/default
  - sudo tar -C /var/lib/apacheds-2.0.0-M19/ -xvf tests/docker-test/default.tar.xz

script:
  - ./tests/travis.sh

addons:
    code_climate:
        repo_token: b33b09a1d0c857fc887313807c745510a8f5658e521ec38f31b8e1288d8cbd07
